### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by JonahWeaver** [JonahWeaver/Subterrania#1]
- [ ] #2  Implement basic features and organization of logic
- [ ] #4 Implement basic multiplayer features
- [ ] Implement unit testing system for ensuring features don't break functionality or cause regressions
- [ ] #3 Polish Inventory system, implement equipment, and allow for dynamic creation of inventory/equipment UI
- [ ] Create save system, testing system for pulling and trying snapshots of the game
- [ ] Basic AI for enemies and NPCs
- [ ] Allow for miscellaneous interactions with world items
- [ ] Cleanup and fixes
- [ ] Create various rideables/vehicles with individual equipment menus
- [ ] TBD
