### ISSUE TITLE
Milestone 0

### ISSUE THREAD

**Issue by JonahWeaver** [JonahWeaver/Subterrania#2]
- [x] Basic Procedural Generation
- [x] Player Controller
- [x] Block and mining mechanics
- [x] Basic inventory system
- [ ] Improved Sprites
- [ ] Dynamic Texture Atlas In Separate application
- [x] Chunk Optimization
